export const faArrowAltDown: IconDefinition;
export const faArrowAltUp: IconDefinition;
export const faBus: IconDefinition;
export const faBusAlt: IconDefinition;
export const faCar: IconDefinition;
export const faCarSide: IconDefinition;
export const faCircle: IconDefinition;
export const faClock: IconDefinition;
export const faEdit: IconDefinition;
export const faInfoCircle: IconDefinition;
export const faInfoSquare: IconDefinition;
export const faLongArrowRight: IconDefinition;
export const faPrint: IconDefinition;
export const faSack: IconDefinition;
export const faSlash: IconDefinition;
export const faSpinner: IconDefinition;
export const faSpinnerThird: IconDefinition;
export const faThumbsDown: IconDefinition;
export const faThumbsUp: IconDefinition;
export const faTombstone: IconDefinition;
export const faTombstoneAlt: IconDefinition;
export const faUser: IconDefinition;
import { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export const prefix: IconPrefix;
export const fad: IconPack;